// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUBcDqBGAB8xRw96OGU0CU075_Gvl5SNU',
    appId: '1:1070536596024:web:07f70655326c63f61ca4cd',
    messagingSenderId: '1070536596024',
    projectId: 'tila-e973a',
    authDomain: 'tila-e973a.firebaseapp.com',
    storageBucket: 'tila-e973a.firebasestorage.app',
    measurementId: 'G-V85LR9MXTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATZei67kGZhC0qtDegagoJKSEH9JLaXUA',
    appId: '1:1070536596024:android:95814cc9315c49761ca4cd',
    messagingSenderId: '1070536596024',
    projectId: 'tila-e973a',
    storageBucket: 'tila-e973a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDatkFOxtzIjYZeDKHd0zKvG-kWgygShjA',
    appId: '1:1070536596024:ios:f867b23df8e7e5b91ca4cd',
    messagingSenderId: '1070536596024',
    projectId: 'tila-e973a',
    storageBucket: 'tila-e973a.firebasestorage.app',
    iosBundleId: 'com.example.tilaApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDatkFOxtzIjYZeDKHd0zKvG-kWgygShjA',
    appId: '1:1070536596024:ios:f867b23df8e7e5b91ca4cd',
    messagingSenderId: '1070536596024',
    projectId: 'tila-e973a',
    storageBucket: 'tila-e973a.firebasestorage.app',
    iosBundleId: 'com.example.tilaApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUBcDqBGAB8xRw96OGU0CU075_Gvl5SNU',
    appId: '1:1070536596024:web:7d6c0fc5be8108151ca4cd',
    messagingSenderId: '1070536596024',
    projectId: 'tila-e973a',
    authDomain: 'tila-e973a.firebaseapp.com',
    storageBucket: 'tila-e973a.firebasestorage.app',
    measurementId: 'G-BMS4NXECNJ',
  );
}
